version: '3.8'

services:
  postgres:
    image: docker.io/postgres:15
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd
    ports:
      - 5432:5432
    volumes:
      - kc-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    environment:
      # HTTP_PROXY: http://proxy:3128
      # HTTPS_PROXY: http://proxy:3128
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: '5432'
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd
      KC_PROXY: edge
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_ADMIN_URL: 'http://localhost/kc'
      KC_HOSTNAME_URL: 'http://localhost/kc'
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_THEME_WELCOME_THEME: scim
      KC_SPI_REALM_RESTAPI_EXTENSION_SCIM_LICENSE_KEY: eyJhbGciOiJFUzUxMiJ9.eyJpc3MiOiJwYXNjYWwga251ZXBwZWwiLCJzdWIiOiI2OTkiLCJhdWQiOiI2OTkiLCJleHAiOjE3MTEyMzg0MDB9.Ac_jhE8ay2JeOWqKfwdeTLQ_5BJK_bU9a635WhucEvNxx6I8B-A2V_buLiLKoxU4khWryoR18Gm4mH5aBvcq4YEqAeDUcbH6V73xD55FWQK16NaKsAm6Krpt-p3ffD4PBLweqfnRa5Bhld36aaIdrUZgp2rCHjB_XBVORkBmM0dIo02F 		
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./providers:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes
      - ./certs:/opt/keycloak/certs

volumes:
  kc-data:
    name: keycloak-workshop-pg-data
